import { StyleSheet } from "react-native";
import colors from "../../../styles/colors";
import fontFamily from "../../../styles/fontFamily";
import {
  moderateScale,
  moderateScaleVertical,
  height,
  textScale,
  width,
} from "../../../styles/responsiveSize";

export const styles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: colors.white },
  bodyContainer: {
    top: moderateScaleVertical(10),
    right: moderateScale(10),
    left: moderateScale(10),
    bottom: 0,
    position: "absolute",
    //backgroundColor: "#f9f9f9",
    borderTopRightRadius: moderateScale(10),
    borderTopLeftRadius: moderateScale(10),
    padding: moderateScale(10),
  },
  bodyHeaderContainer: {
    flexDirection: "row",
  },
  headerLeftSideContainer: {
    flexDirection: "row",
    alignItems: "center",
    flex: 0.8,
  },
  menuContainerStyle: {
    backgroundColor: colors.white,
    borderRadius: moderateScale(50),
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 10,
    width: moderateScale(width / 10),
    height: moderateScale(width / 10),
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: moderateScale(10),
  },
  backArrowIconStyle: {
    width: moderateScale(width / 12),
    height: moderateScale(width / 12),
    // marginRight: moderateScale(10),
    justifyContent: "center",
    // backgroundColor:colors.darkBlue
  },

  backArrowIcon: {
    width: moderateScale(width / 16),
    height: moderateScale(width / 16),
    tintColor: colors.darkBlue,
    marginRight: moderateScale(10),
  },
  headerIcon: {
    width: moderateScale(width / 20),
    height: moderateScale(width / 20),
  },
  empNameStyle: {
    fontSize: textScale(15),
    fontFamily: fontFamily.robotoRegular,
    color: colors.black,
    textTransform: "capitalize",
    marginLeft: moderateScale(10),
  },
  shiftText: {
    fontSize: textScale(12),
    fontFamily: fontFamily.robotoRegular,
    color: colors.black,
    textTransform: "capitalize",
  },
  headerRightSideContainer: {
    flex: 0.2,
    alignItems: "center",
    justifyContent: "center",
  },
  bodyDetailsContainer: {
    //marginTop: moderateScaleVertical(55),
    //paddingHorizontal: 8,
  },
  renderItemMainContainer: {
    marginHorizontal: moderateScale(5),
    marginTop: moderateScaleVertical(10),
    minWidth: moderateScale(width / 2.8),
  },
  renderItemMainContainerActive: {
    marginHorizontal: moderateScale(5),
    minWidth: moderateScale(width / 2.8),
    marginTop: moderateScaleVertical(10),
    backgroundColor: colors.lightGrayBackground,
  },
  activeCard: {
    height: moderateScale(3),
    backgroundColor: colors.logoutColor,
  },
  activeCard_2: {
    height: moderateScale(3),
    backgroundColor: colors.loginColor,
  },
  renderItemContainer: {
    backgroundColor: colors.white,
    borderRadius: moderateScale(8),
    marginHorizontal: moderateScale(10),
    marginTop: moderateScaleVertical(10),
  },
  shadowProp: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  renderItemTopContainer: {
    marginHorizontal: moderateScale(10),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingRight: moderateScale(5),
    paddingVertical: moderateScaleVertical(5),
  },
  loginLogoutImgStyle: {
    width: moderateScale(width / 16),
    height: moderateScale(width / 16),
    marginRight: moderateScale(5),
  },
  renderItemTopRightContainer: {
    // alignItems:'center',
    justifyContent: "center",
  },
  shiftTimeText: {
    color: colors.gray,
    fontSize: textScale(16),
    fontFamily: fontFamily.robotoMedium,
  },
  shiftNameConatiner: {
    flexDirection: "row",
    alignItems: "center",
  },
  shiftIconStyle: {
    width: moderateScale(width / 22),
    height: moderateScale(width / 22),
    marginRight: moderateScale(5),
  },
  renderItemBottomContainer: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.logoutColor,
    borderBottomEndRadius: moderateScale(8),
    borderBottomLeftRadius: moderateScale(8),
    paddingVertical: moderateScaleVertical(4),
  },
  renderItemBottomContainer_2: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.loginColor,
    borderBottomEndRadius: moderateScale(8),
    borderBottomLeftRadius: moderateScale(8),
    paddingVertical: moderateScaleVertical(4),
  },
  renderItemDateText: {
    color: colors.white,
    fontSize: textScale(12),
    fontFamily: fontFamily.robotoMedium,
  },
  rosterDetailsContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: moderateScaleVertical(10),
    backgroundColor: colors.white,
    borderRadius: moderateScale(12),
    marginHorizontal: moderateScale(10),
    paddingRight: moderateScale(10),
  },
  rosterImgStyle: {
    width: moderateScale(width / 3),
    height: moderateScale(width / 6),
  },
  cardShadowProp: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  rosterTextContainerStyle: {
    flexDirection: "row",
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  rosterNumStyle: {
    color: colors.black,
    fontSize: textScale(18),
    fontFamily: fontFamily.robotoMedium,
    marginRight: moderateScale(5),
  },
  rosterTextStyle: {
    color: colors.black,
    fontSize: textScale(16),
    fontFamily: fontFamily.robotoRegular,
    marginRight: moderateScale(10),
  },
  iconContainerStyle: {
    backgroundColor: colors.lightSkyBlueBackground,
    padding: moderateScale(5),
    borderRadius: moderateScale(50),
  },
  iconStyle: {
    tintColor: colors.loginColor,
    width: moderateScale(width / 12),
    height: moderateScale(width / 12),
  },
  cardMainContainer: {
    flexDirection: "row",
    marginTop: moderateScale(20),
  },
  rideDetailsContainer: {
    backgroundColor: colors.white,
    borderRadius: moderateScale(8),
    marginHorizontal: moderateScale(10),
    flex: 0.5,
  },
  dateAndTimeContainer: {
    paddingHorizontal: 10,
    alignItems: "center",
    marginTop: 10,
  },
  dateText: { fontSize: 20, color: colors.darkBlueColor, fontWeight: "500" },
  scrollContainerStyle: {
    marginBottom: 100,
  },
  devider: {
    height: 0.8,
    width: "100%",
    backgroundColor: colors.lightGary,
    marginTop: 10,
  },
  containerBottomMargin: { marginBottom: 10 },
  headerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 10,
  },
  vaccineIconContainer: {
    height: 30,
    width: 30,
    borderWidth: 0.5,
    borderColor: colors.lightBackground,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 5,
  },
  vaccineIconStyle: { height: 20, width: 20 },
  titleText: {
    color: colors.black,
    fontSize: 18,
    fontWeight: "400",
  },
  drawerIconContainer: {
    backgroundColor: "white",
    height: 40,
    width: 40,
    borderWidth: 0.5,
    borderColor: colors.lightBackground,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  dropdown: {
    backgroundColor: "transparent",
    borderRadius: moderateScale(8),
    // maxWidth: moderateScale(width / 2.9),
    // minWidth: moderateScale(width / 2.9),
    //marginTop: 20,
    borderColor: colors.white,
    borderWidth: 1,
    //paddingHorizontal: 20,

    //marginRight: 10,
  },
  dropdownRennderItemContainer: {
    marginVertical: moderateScaleVertical(5),
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 2,
  },
  dropdownRightIconContainer: {
    height: 35,
    width: 40,
    borderWidth: 0.5,
    borderColor: colors.lightBackground,
    borderRadius: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  dropdownIconStyle: { height: 16, width: 16 },
  placeholderStyle: {
    fontSize: textScale(9),
    fontFamily: fontFamily.robotoMedium,
    color: "transparent",
    marginLeft: moderateScale(8),
    textAlign: "center",
  },
  selectedTextStyle: {
    fontSize: textScale(12),
    fontFamily: fontFamily.robotoMedium,
    color: "transparent",
    marginLeft: moderateScale(4),
    textAlign: "center",
  },
  itemStyle: {
    color: colors.black,
  },
});
