import { StyleSheet } from "react-native";
import colors from "../../../styles/colors";
import {
  moderateScale,
  moderateScaleVertical,
  height,
  width,
  textScale,
} from "../../../styles/responsiveSize";
import fontFamily from "../../../styles/fontFamily";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.lightGary,
  },
  headerStyle: {
    flex: 0.09,
    flexDirection: "row",
  },
  headerLeftSide: {
    flex: 0.5,
    backgroundColor: "#fff",
    borderTopRightRadius: moderateScale(50),
    borderBottomRightRadius: moderateScale(50),
    justifyContent: "center",
  },
  appLogo: {
    width: moderateScale(width / 3),
    marginLeft: moderateScale(15),
  },
  headerRightSide: {
    flex: 0.5,
    justifyContent: "center",
    alignItems: "flex-end",
  },
  menuIcon: {
    width: 20,
    height: 20,
    tintColor: "black",
  },
  tripDetails: {
    flex: 0.05,
    backgroundColor: colors.lightOrange,
    flexDirection: "row",
  },
  tripCountContainer: {
    flex: 0.5,
    justifyContent: "center",
    marginLeft: moderateScale(15),
  },
  tripCountText: {
    color: colors.white,
    fontSize: textScale(13),
    fontFamily: fontFamily.robotoMedium,
  },
  callEmpContainer: {
    flex: 0.5,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginRight: moderateScale(15),
  },
  callEmpText: {
    color: colors.white,
    fontSize: textScale(13),
    fontFamily: fontFamily.robotoMedium,
  },
  callEmpIcon: {
    width: moderateScale(width / 18),
    height: moderateScale(width / 18),
  },
  mapContainer: {
    flex: 1,
  },
  bottomViewConatiner: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    // backgroundColor: colors.white,
    // width: width,
    // borderTopLeftRadius: 45,
    // borderTopRightRadius: 45,
    // paddingHorizontal:moderateScale(15),
    paddingVertical: moderateScaleVertical(15),
  },
  empDetailsContainer: {
    borderRadius: moderateScale(4),
    backgroundColor: colors.darkBlue,
    justifyContent: "center",
  },
  empDetailsHeader: {
    flexDirection: "row",
    marginVertical: moderateScaleVertical(10),
  },
  empDetailsHeaderLeft: {
    flex: 0.65,
    flexDirection: "row",
    marginLeft: moderateScale(20),
    alignItems: "center",
  },
  empPic: {
    width: moderateScale(width / 12),
    height: moderateScale(width / 12),
  },
  empNameConatiner: {
    marginLeft: moderateScale(10),
  },
  // empNameText: {
  //   color: colors.white,
  //   fontSize: textScale(14),
  //   fontFamily: fontFamily.robotoMedium,
  //   color: colors.blueBackground,
  //   textDecorationLine: 'underline',
  // },
  destinationTimeText: {
    fontSize: textScale(10),
    fontFamily: fontFamily.robotoRegular,
    color: colors.white,
  },
  empDetailsHeaderRight: {
    flex: 0.35,
    borderLeftColor: colors.mediumLightBlue,
    borderLeftWidth: 2,
    justifyContent: "center",
    alignItems: "center",
  },
  trackDriverText: {
    color: colors.white,
    fontSize: textScale(12),
    fontFamily: fontFamily.robotoMedium,
  },
  empDetailsBottom: {
    backgroundColor: colors.black,
    flexDirection: "row",
    paddingVertical: moderateScaleVertical(5),
    marginVertical: moderateScaleVertical(5),
  },
  empDetailsBottomLeft: {
    flex: 0.5,
    alignItems: "flex-start",
    marginLeft: moderateScale(20),
  },
  empDetailsBottomRight: {
    flex: 0.5,
    alignItems: "flex-end",
    marginRight: moderateScale(20),
  },
  empTripIDText: {
    color: colors.white,
    fontSize: textScale(12),
    fontFamily: fontFamily.robotoBold,
  },
  empTripPickTypeText: {
    color: colors.white,
    fontSize: textScale(10),
    fontFamily: fontFamily.robotoMedium,
  },
  tripScheduleContainer: {
    borderRadius: moderateScale(4),
    backgroundColor: colors.darkBlue,
    marginVertical: moderateScaleVertical(10),
  },
  tripScheduleHeader: {
    flexDirection: "row",
    marginLeft: moderateScale(15),
    marginVertical: moderateScaleVertical(5),
    alignItems: "center",
  },
  tripScheduleHeading: {
    color: colors.lightOrange,
    fontSize: textScale(14),
    fontFamily: fontFamily.robotoMedium,
  },
  tripScheduleText: {
    fontSize: textScale(12),
    fontFamily: fontFamily.robotoRegular,
    color: colors.white,
    marginLeft: moderateScale(10),
    alignSelf: "flex-end",
  },
  nextPickDetailsContainer: {
    backgroundColor: colors.mediumBlue,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: moderateScaleVertical(8),
    borderRadius: moderateScale(4),
  },
  nextPickDetailsLeftSide: {
    flex: 0.7,
    marginLeft: moderateScale(15),
  },
  nextPickupLocText: {
    color: colors.white,
    fontSize: textScale(12),
    fontFamily: fontFamily.robotoRegular,
  },
  nextPassengerDetailsContainer: {
    flexDirection: "row",
  },
  nextPassengerHeading: {
    color: colors.white,
    fontSize: textScale(12),
    fontFamily: fontFamily.robotoRegular,
  },
  nextPassengerName: {
    color: colors.lightOrange,
    fontSize: textScale(12),
    fontFamily: fontFamily.robotoRegular,
  },
  nextPickDetailsRightSide: {
    flex: 0.3,
    justifyContent: "flex-end",
  },
  etaText: {
    fontSize: textScale(12),
    color: colors.white,
    fontFamily: fontFamily.robotoRegular,
  },
  btnStyle: {
    flexDirection: "row",
    paddingVertical: moderateScaleVertical(10),
    borderRadius: moderateScale(4),
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.lightOrange,
  },
  btnTextStyle: {
    color: colors.white,
    fontSize: textScale(12),
    fontFamily: fontFamily.robotoBold,
  },
  iconStyle: {
    width: moderateScale(width / 12),
    height: moderateScale(width / 18),
    marginRight: moderateScale(10),
  },
  Modal: {
    backgroundColor: "#fff",
    marginTop: 0,
    maxHeight: 400,
    bottom: 0,
    // position: 'absolute'
  },
  containerContent: { flex: 1 },
  containerHeader: {
    flex: 1,
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    height: 40,
    backgroundColor: "#F1F1F1",
  },
  headerContent: {
    marginTop: 0,
  },
  backBtnStyle: {
    paddingVertical: moderateScaleVertical(8),
    paddingHorizontal: moderateScale(30),
    borderRadius: moderateScale(4),
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "flex-end",
    backgroundColor: colors.darkBlue,
  },
  backBtnTextStyle: {
    color: colors.white,
    fontSize: textScale(15),
    fontFamily: fontFamily.robotoMedium,
    textTransform: "uppercase",
  },
  submitBtnStyle: {
    paddingVertical: moderateScaleVertical(8),
    paddingHorizontal: moderateScale(30),
    borderRadius: moderateScale(4),
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "flex-end",
    backgroundColor: colors.darkGray,
  },
  submitBtnTextStyle: {
    color: colors.white,
    fontSize: textScale(15),
    fontFamily: fontFamily.robotoMedium,
    textTransform: "uppercase",
  },
  bottomView: {
    position: "absolute",
    bottom: 20,
    left: 30,
    right: 30,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  empDetails: {
    flexDirection: "row",
    marginHorizontal: moderateScale(30),
    marginBottom: moderateScaleVertical(12),
    //alignItems:'center',
    marginTop: 10,
    //alignSelf: 'center'
  },
  empLable: {
    // flex: 2,
    fontSize: textScale(12),
    fontFamily: fontFamily.robotoMedium,
    color: colors.themeColor,
  },
  empText: {
    // flex: 2,
    fontSize: textScale(12),
    fontFamily: fontFamily.robotoMedium,
    color: colors.black,
    marginLeft: moderateScale(10),
  },

  timeText: {
    color: colors.black,
    fontWeight: "bold",
    fontSize: 20,
    marginLeft: 10,
  },

  newRow: { marginVertical: 20 },

  bottomSheetContainer: {
    flex: 1,
    backgroundColor: colors.modalColor,
    justifyContent: "flex-end",
  },
  bottomSheetInsideContainer: {
    width: "100%",
    backgroundColor: colors.white,
    paddingBottom: 30,
  },
  bottomSheetNewRowContainer: { paddingHorizontal: 20, marginTop: 20 },
  otpMainContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  otpContainer: { width: "50%" },
  otpImageContainer: {
    width: "50%",
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "red",
  },
  otpImageStyle: { height: 150, width: "90%" },
  empVerfText: {
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 16,
    color: "#176178",
  },
  bottomSheetDividerContainer: { flexDirection: "row", alignItems: "center" },
  bottomSheetDividerStyle: {
    height: 0.3,
    width: "45%",
    backgroundColor: colors.lightGray,
  },
  orTextContainerStyle: {
    width: "10%",
    height: 35,
    borderWidth: 1,
    borderColor: colors.lightGary,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginTop: -10,
  },
  orTextStyle: { color: colors.black, fontSize: 12, fontWeight: "bold" },
  qrImageContainer: { justifyContent: "center", alignItems: "center" },
  qrImageStyle: { height: 230, width: 230 },
  showQrCodeText: {
    fontSize: 16,
    textAlign: "center",
    color: colors.darkSkyBlue,
    fontWeight: "bold",
    marginTop: -15,
  },
  otpTextInputContainer: { height: 80 },
  otpCellStyle: {
    borderBottomWidth: 2,
    borderColor: "gray",
    width: 40,
  },
  otpFocusCellStyle: {
    borderColor: "black",
  },
  empDetailMoalContainer: {
    paddingHorizontal: 20,
    //marginTop: 15,
  },
  empDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    //height: "28%",
  },
  timerContainer: {
    width: "20%",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: "green",
    height: 70,
    borderRadius: 50,
  },
  timeMinute: { fontSize: 20, fontWeight: "bold", color: "black" },

  detailContainer: {
    width: "100%",
    paddingHorizontal: 10,
    marginLeft: -10,
    //backgroundColor: "green",
  },
  empModalHeight: { height: "50%" },
  vaccinatedContainer: {
    width: "20%",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 5,
    borderColor: "green",
    height: 70,
    borderRadius: 50,
  },
  empNameText: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.blueBackground,
    textDecorationLine: "underline",
  },
  empLocationContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
  },
  buttonContainer: {
    flexDirection: "row",
    //marginTop: 10,
    justifyContent: "space-between",
  },
  continueButton: {
    backgroundColor: colors.blueBorderColor,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  notSeenButton: {
    backgroundColor: "transparent",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "grey",
  },
  continueButtonText: { fontSize: 13, color: colors.white },
  notSeenBtnTextStyle: { fontSize: 13 },
  chatBoxContainer: {
    backgroundColor: colors.lightGary,
    //marginTop: 20,
    height: 180,
    // paddingHorizontal: 10,
    paddingVertical: 10,
    marginTop: 20,
  },
  textInputBox: {
    width: "100%",
    height: 65,
    position: "absolute", //Here is the trick
    bottom: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 10,
    backgroundColor: colors.lightGary,
  },
  callButtonContainer: {
    height: 50,
    width: "15%",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.darkGray,
    backgroundColor: colors.white,
  },
  textInputContainer: {
    width: "80%",
    height: 50,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.darkGray,
    backgroundColor: colors.white,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 10,
  },
  textInputStyle: { height: "100%", width: "80%" },
  chatMessageLeftContainer: { width: "100%", marginTop: 10 },
  chatMessageRightContainer: {
    width: "100%",
    alignItems: "flex-end",
    marginTop: 5,
  },
  chatMessageLeftBox: {
    width: "70%",
    //backgroundColor: "red",
    flexDirection: "row",
    alignItems: "center",
  },
  chatMessageRightBox: {
    width: "70%",
    //backgroundColor: "green",
    flexDirection: "row-reverse",
    alignItems: "center",
  },
  messageLeftContainer: {
    backgroundColor: colors.blueBorderColor,
    width: "100%",
    paddingVertical: 5,
    paddingHorizontal: 5,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    //borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  messageRightContainer: {
    backgroundColor: colors.white,
    width: "100%",
    paddingVertical: 5,
    paddingHorizontal: 5,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    marginRight: 10,
    //borderBottomRightRadius: 10,
  },
  leftMessage: { color: colors.white },
  rightMessage: { textAlign: "right" },
  swipeToRightButtonBox: {
    width: "80%",
    backgroundColor: colors.greenColor,
    height: 50,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "green",
  },
  swipeToRightIconBox: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "green",
    borderRadius: 10,
  },
  swipeToRightButtonTextContainer: {
    width: "75%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  swipToRightTextStyle: {
    color: colors.white,
    fontSize: 20,
    fontWeight: "bold",
  },
  nextPickupLocationContainer: {
    //height: "30%",
    width: "100%",
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginTop: 5,
  },
  nextPickupLocationText: {
    fontSize: 18,
    color: colors.themeColor,
  },
  vaccinationImgContainer: {
    zIndex: 99,
    width: "20%",
    //marginRight: moderateScale(-20),
  },
  vaccinationImgStyle: {
    width: moderateScale(width / 5.5),
    height: moderateScale(width / 5.5),
  },
  driverImg: {
    position: "absolute",
    width: moderateScale(width / 7.9),
    height: moderateScale(width / 7.9),
    top: moderateScale(width / 36),
    left: moderateScale(width / 37.5),
    borderRadius: moderateScale(50),
  },

  noShowOutsideContainer: {
    height: 70,
    width: 70,
    borderRadius: 50,
    borderWidth: 6,
    borderColor: colors.darkYellow,
    justifyContent: "center",
    alignItems: "center",
  },
  noShowInsieContainer: {
    height: 50,
    width: 50,
    borderRadius: 50,
    borderWidth: 4,
    borderColor: colors.darkOrange,
    justifyContent: "center",
    alignItems: "center",
  },
  noTextStyle: {
    color: colors.black,
    fontSize: 7,
    fontWeight: "bold",
  },
  showTextStyle: {
    color: colors.black,
    fontSize: 12,
    fontWeight: "bold",
    marginTop: -5,
  },
  ratingContainerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: -5,
  },
  ratingContainer: {
    marginTop: 5,
    alignItems: "flex-start",
    flexDirection: "row",
  },
  ratingText: { marginLeft: 20, marginTop: 5, color: "black" },
  addressTextStyle: {
    fontSize: 12,
    marginLeft: 5,
    color: colors.blueBackground,
    textDecorationLine: "underline",
  },
  messageListContainer: { flex: 1, marginBottom: 60 },
  phoneIconStyle: { height: 24, width: 24, tintColor: colors.black },
  sendIconStyle: { height: 20, width: 20, tintColor: colors.darkGray },
  nextPickupLocationRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: -20,
  },
  avatarIconContainer: {
    height: 40,
    width: 40,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 30,
  },
  avatarIconStyle: { height: 30, width: 30 },
  deliveryInfoIconStyle: { height: 100, width: "100%" },
  deliveryInfoIconContainer: { width: "46%" },
  estimateTimeContainer: {
    height: 15,
    width: "80%",
    backgroundColor: colors.blueBorderColor,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
    marginTop: 3,
  },
  estimateTimeText: { fontSize: 9, color: colors.white },
  nextPickupAddressText: { fontSize: 9, fontWeight: "300" },
  nextpickupAddressContainer: {
    width: "75%",
    //backgroundColor: "green",
    height: 30,
    // justifyContent: "center",
    // alignItems: "center",
    marginLeft: 5,
  },
  nextPickupLocationIconStyle: {
    height: 25,
    width: 25,
  },
  nextPickupLocationIconContainer: {
    width: "25%",
    //backgroundColor: "red",
    height: 30,
  },
  insideTruckContainer: {
    height: 35,
    width: 105,
    //backgroundColor: "red",
    marginLeft: 10,
    marginTop: 32,
    flexDirection: "row",
    alignItems: "center",
  },
  deliveryTruckIconStyle: {
    height: 115,
    width: "100%",
  },
  deliveryTruckContainer: { width: "52%" },

  securityIconContainer: {
    marginTop: -30,
    height: 25,
    width: 25,
    backgroundColor: colors.white,
    marginHorizontal: 15,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  employeeVerificationTextStyle: {
    textAlign: "center",
    fontWeight: "600",
    color: colors.darkSkyBlue,
  },
  otpCodeContainer: { width: "100%" },
  swipeToRightButtonContainer: {
    width: "100%",
    height: 70,
    //backgroundColor: colors.white,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 0,
  },
  qrCodeModalMainContainer: { flex: 1 },
  qrCodeBottomModalContainer: {
    justifyContent: "flex-end",
    alignItems: "flex-end",
    flex: 1,
    backgroundColor: colors.modalColor,
  },
  qrCodeModalContentContainer: {
    width: "100%",
    backgroundColor: colors.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 20,
  },
  errorMessageContainer: {
    justifyContent: "center",
    alignItems: "center",
  },
  errorMessageText: { color: colors.redColor, fontSize: 16 },
  qrCodeAddressContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  qrCodeAddressContainerRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  qrCodeFromPointIndicator: {
    height: 6,
    width: 6,
    backgroundColor: colors.greenColor,
    borderRadius: 10,
  },
  qrCodeAddressText: {
    fontSize: 12,
    marginLeft: 5,
    color: colors.darkGray,
  },
  qrCodeDotInticator: {
    height: 5,
    width: 5,
    backgroundColor: colors.lightGray,
    borderRadius: 10,
    marginVertical: 1,
  },
  qrCodeToAddressRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  qrCodeToAddressIndicator: {
    height: 6,
    width: 6,
    backgroundColor: colors.orangeColor,
    borderRadius: 10,
  },
  qrCodeEnterOtpText: { color: colors.black },
  crossIconStyle: {
    height: 20,
    width: 20,
    tintColor: colors.SOSSwipeBottonColor1,
  },
});
