import { StyleSheet } from "react-native";
import {
  moderateScale,
  moderateScaleVertical,
  textScale,
  width,
  height,
} from "../../../styles/responsiveSize";
import colors from "../../../styles/colors";
import fontFamily from "../../../styles/fontFamily";

export const styles = StyleSheet.create({
  topContainer: {
    height: moderateScale(height / 3.5),
    backgroundColor: colors.black,
  },
  topContentContainer: {
    marginHorizontal: moderateScale(15),
    marginTop: moderateScaleVertical(10),
    marginBottom: moderateScaleVertical(20),
  },
  titleStyle: {
    fontSize: textScale(28),
    color: colors.white,
    fontFamily: fontFamily.robotoMedium,
    marginVertical: moderateScaleVertical(10),
  },
  descriptionStyle: {
    fontSize: textScale(14),
    color: colors.whiteSmoke,
    fontFamily: fontFamily.robotoRegular,
    marginVertical: moderateScaleVertical(10),
  },
  formContainer: {
    backgroundColor: colors.white,
    marginHorizontal: moderateScale(10),
    paddingVertical: moderateScaleVertical(25),
    paddingHorizontal: moderateScale(20),
    flex: 1,
    top: moderateScaleVertical(-40),
    borderRadius: moderateScale(8),
  },
  inputFieldContainer: {
    alignItems: "center",
    marginTop: moderateScaleVertical(50),
    justifyContent: "center",
  },
  cellStyle: {
    // borderBottomColor: colors.darkBlue,
    // borderBottomWidth: moderateScale(5),
    // alignItems: 'center',
    // justifyContent: 'center',
    // marginBottom: moderateScaleVertical(10),
    width: moderateScale(width / 10),
    borderBottomColor: colors.darkBlue,
    borderBottomWidth: moderateScale(3),
    alignItems: "center",
    justifyContent: "center",
    marginBottom: moderateScaleVertical(10),
  },
  textStyle: {
    // fontSize: textScale(18),
    // color: colors.darkBlue,
    fontSize: textScale(18),
    fontFamily: fontFamily.robotoMedium,
    color: colors.darkBlue,
  },
  bottomView: {
    marginHorizontal: moderateScale(20),
  },
  btnStyle: {
    paddingVertical: moderateScaleVertical(10),
    borderRadius: moderateScale(4),
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.darkBlue,
  },
  btnTextStyle: {
    color: colors.white,
    fontSize: textScale(15),
    fontFamily: fontFamily.robotoMedium,
    textTransform: "uppercase",
  },
  resendOtpBtnContainer: {
    flexDirection: "row",
    //marginTop: moderateScaleVertical(10),
    marginBottom: moderateScaleVertical(56),
    alignSelf: "flex-end",
  },
  resendOtpBtnText: {
    fontSize: textScale(14),
    color: colors.darkBlue,
    fontFamily: fontFamily.robotoBold,
    marginTop: moderateScaleVertical(20),
    fontWeight: "700",
  },
  resendOtpBtnTextDisabled: {
    fontSize: textScale(14),
    color: colors.mediumGray,
    fontFamily: fontFamily.robotoBold,
    fontWeight: "700",
  },
  modalContainer: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    backgroundColor: colors.lightBackground,
    paddingHorizontal: 10,
  },
  modalInsideContainer: {
    //height: "32%",
    width: "85%",
    backgroundColor: colors.white,
    borderRadius: 10,
    paddingTop: 20,
    paddingHorizontal: 20,
    //alignItems: 'center',
  },
  desaibleCancleBtnStyle: {
    borderRadius: moderateScale(24),
    paddingVertical: moderateScaleVertical(5),
    marginVertical: moderateScaleVertical(20),
    marginHorizontal: moderateScaleVertical(10),
    paddingHorizontal: moderateScale(20),
    borderWidth: moderateScale(0.5),
    borderColor: colors.darkRed,
  },
  desaibleCancleBtnTextStyle: {
    color: colors.darkRed,
    fontSize: textScale(14),
    fontFamily: fontFamily.robotoMedium,
    textTransform: "uppercase",
    textAlign: "center",
  },
  submitBtnStyle: {
    borderRadius: moderateScale(24),
    borderWidth: moderateScale(0.5),
    borderColor: colors.darkSkyBlue,
    paddingVertical: moderateScaleVertical(5),
    marginVertical: moderateScaleVertical(20),
    marginHorizontal: moderateScaleVertical(10),
    paddingHorizontal: moderateScale(20),
  },

  desaibleSubmitBtnStyle: {
    borderRadius: moderateScale(24),
    borderWidth: moderateScale(0.5),
    borderColor: colors.mediumGray,
    paddingVertical: moderateScaleVertical(5),
    marginVertical: moderateScaleVertical(20),
    marginHorizontal: moderateScaleVertical(10),
    paddingHorizontal: moderateScale(20),
  },

  desaibleSubmitBtnTextStyle: {
    color: colors.mediumGray,
    fontSize: textScale(14),
    fontFamily: fontFamily.robotoMedium,
    textTransform: "uppercase",
    textAlign: "center",
  },
  submitBtnTextStyle: {
    color: colors.darkSkyBlue,
    fontSize: textScale(14),
    fontFamily: fontFamily.robotoMedium,
    textTransform: "uppercase",
    textAlign: "center",
  },
  logoutPopupContainer: { flex: 1 },
  logoutConfirmationContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  confirmationTextStyle: {
    color: colors.black,
    textTransform: "capitalize",
    fontSize: textScale(12),
    fontFamily: fontFamily.robotoRegular,
  },
  logoutConfirmationButtonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: moderateScaleVertical(10),
    marginHorizontal: moderateScale(20),
  },
  OtpMainContainer: { flex: 1, backgroundColor: colors.lightGary },
});
