export default {
  notoSansBold: 'NotoSans-Bold',
  notoSansBoldItalic: 'NotoSans-BoldItalic',
  notoSansItalic: 'NotoSans-Italic',
  notoSansRegular: 'NotoSans-Regular',
  robotoBlack: 'Roboto-Black',
  robotoBlackItalic: 'Roboto-BlackItalic',
  //robotoBold: 'Roboto-Bold',
  robotoBoldItalic: 'Roboto-BoldItalic',
  robotoItalic: 'Roboto-Italic',
  robotoLight: 'Roboto-Light',
  robotoLightItalic: 'Roboto-LightItalic',
  robotoMedium: 'System',
  robotoMediumItalic: 'Roboto-MediumItalic',
  robotoRegular: 'Roboto-Regular',
  robotoThin: 'Roboto-Thin',
  robotoThinItalic: 'Roboto-ThinItalic',
};
