import { StyleSheet } from "react-native";
import colors from "../../../styles/colors";
import {
  moderateScale,
  moderateScaleVertical,
  height,
  width,
  textScale,
} from "../../../styles/responsiveSize";
import fontFamily from "../../../styles/fontFamily";

export const styles = StyleSheet.create({
  bottomContainer: {
    flex: 1,
    width: "100%",
    backgroundColor: colors.lightGary,
    alignItems: "center",
  },
  contentSectionContainer: {
    flex: 1,
    width: width - 15,
    backgroundColor: colors.white,
    marginTop: -100,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    paddingBottom: 20,
  },
  tabContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  activeButtonStyle: {
    borderBottomWidth: 2,
    borderColor: colors.themeColor,
    width: "50%",
    paddingVertical: 10,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  deactiveButtonStyle: {
    borderBottomWidth: 2,
    borderColor: colors.lightGary,
    width: "50%",
    paddingVertical: 10,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  activeTextStyle: {
    color: colors.themeColor,
    fontSize: 16,
  },
  deactiveTextStyle: {
    color: colors.darkGray,
    fontSize: 16,
  },
  cardContainer: {
    borderColor: colors.lightBorderColor,
    borderWidth: 2,
    borderRadius: 14,
    marginTop: 15,
    marginHorizontal: 10,
  },
  detailRowStyle: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 10,
    borderRadius: 10,
    paddingVertical: 12,
  },
  commentConntainer: {
    height: 35,
    paddingHorizontal: 10,
    justifyContent: "center",
  },
  horizontalDevider: {
    height: 1,
    backgroundColor: colors.lightGary,
    width: "100%",
  },
  detailBox: { paddingHorizontal: 10, paddingVertical: 10 },
  actionIconContainer: {
    height: 25,
    width: 25,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: colors.lightBorderColor,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.white,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  actionIconStyle: { height: 13, width: 13, transform: [{ rotate: "270deg" }] },
  titleText: { fontSize: 13, color: colors.black },
  heading: {
    fontSize: 16,
    color: colors.black,
  },
  description: {
    fontSize: 14,
    color: colors.black,
  },
  detailContainer: {
    width: "60%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  leftBox: { width: "50%" },
  rightBox: { width: "50%" },
  iconConntainer: {
    width: "40%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  iconStyle: { height: 20, width: 20 },
  tripDetailContainer: {
    width: "73%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  amountDetailConntainer: {
    width: "25%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  tripIconBox: { width: "15%" },
  tripDetailBox: { width: "83%" },
  tripIconStyle: { height: 30, width: 30 },
  verticalDevider: {
    height: 15,
    width: 2,
    backgroundColor: colors.lightGary,
    marginHorizontal: 5,
  },
  tripDateAndIdText: {
    fontSize: 10,
    color: colors.black,
    marginLeft: 5,
  },
  dateText: {
    fontSize: 10,
    color: colors.black,
  },
  tripIdContainer: { flexDirection: "row", marginTop: 3 },
  tableListText: {
    color: colors.black,
    fontSize: 11,
    fontWeight: "500",
  },
  tableListDetailText: {
    color: colors.black,
    fontSize: 11,
  },
  statusIcon: {
    height: 20,
    width: 20,
  },
  notFoundContainer: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  notFoundText: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.black,
  },
  fromToAddressContainer: {
    width: "83%",
  },
  fromToContainer: { width: "100%" },
  fromAddressContainer: {
    flexDirection: "row",
    alignItems: "center",
    //marginBottom: 2,
  },
  toAddressIndicator: {
    height: 5,
    width: 5,
    backgroundColor: colors.greenColor,
    borderRadius: 10,
  },
  addressText: {
    fontSize: textScale(9),
    marginLeft: 5,
    color: colors.gray,
    fontFamily: fontFamily.robotoRegular,
  },
  dotIndicatorContainer: { flexDirection: "row" },
  dotIndicator: {
    height: 3,
    width: 3,
    backgroundColor: colors.lightGray,
    marginLeft: 1,
    borderRadius: 10,
    marginVertical: 1,
  },
  toAddressContainer: {
    flexDirection: "row",
    //marginTop: 2,
    alignItems: "center",
  },
  fromAddressIndicator: {
    height: 5,
    width: 5,
    backgroundColor: colors.orangeColor,
    borderRadius: 10,
  },
  fromAddressTextContainer: {
    flexDirection: "row",
    //justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  toPointTextContainer: { width: "100%" },
  amountText: { fontSize: 12, color: colors.black },
});
