import { StyleSheet } from "react-native";
import colors from "../../../styles/colors";
import { height, moderateScale, width } from "../../../styles/responsiveSize";

export const styles = StyleSheet.create({
  topContainer: { height: 150 },
  bgImageStyle: {
    height: "100%",
    width: "100%",
    backgroundColor: colors.themeColor,
  },
  backButtonStyle: {
    height: 40,
    width: 40,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: 30,
  },
  bottomContainer: {
    height: "80%",
    width: "100%",
    backgroundColor: colors.lightGary,
    alignItems: "center",
  },
  contentSectionContainer: {
    width: "95%",
    backgroundColor: colors.white,
    marginTop: -90,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    flex: 1,
  },
  contentRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginTop: 20,
  },
  checkboxContainer: {
    width: "5%",
    height: 30,
    alignItems: "center",
  },
  contentContainer: { width: "80%" },
  iconContainer: { width: "10%", alignItems: "flex-end" },
  checkBox: {
    height: 20,
    width: 20,
    borderWidth: 2,
    borderColor: colors.darkGray,
  },
  iconStyle: {
    height: 20,
    width: 20,
    borderRadius: 20,
    backgroundColor: colors.darkGray,
    justifyContent: "center",
    alignItems: "center",
  },
  contentText: {
    fontSize: 16,
    fontWeight: "500",
    color: colors.black,
    textTransform: "capitalize",
  },
  divider: {
    height: 1,
    width: "100%",
    backgroundColor: colors.lightGary,
    marginBottom: 5,
    marginTop: 15,
  },
  newRowContainer: {
    marginTop: 30,
    paddingHorizontal: 20,
  },
  covidRuleText: {
    //fontWeight: "500",
    color: colors.black,
  },
  learnMoreRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  learnMoreText: {
    fontWeight: "500",
    fontSize: 16,
    color: colors.black,
  },
  covidSiteText: {
    fontWeight: "500",
    fontSize: 16,
    textDecorationLine: "underline",
    marginLeft: 5,
    color: colors.black,
  },
  agreeButton: {
    backgroundColor: colors.themeColor,
    width: "60%",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 20,
  },
  agreeButtonText: {
    color: colors.white,
    fontWeight: "800",
    fontSize: 16,
  },
  buttonContainer: {
    marginTop: 30,
    paddingHorizontal: 20,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 30,
  },
  requiredText: {
    color: "red",
    fontSize: 12,
    marginTop: 10,
  },
  takePhotoTextContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  varificationText: {
    color: colors.orangeColor,
    fontSize: 12,
  },
  backButtonContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
    paddingHorizontal: 20,
  },
  headerTitleText: {
    color: colors.white,
    marginLeft: 10,
    fontSize: 18,
    fontWeight: "bold",
  },
  alertIconStyle: {
    height: 15,
    width: 15,
    tintColor: colors.orangeColor,
  },
  checkIconStyle: { height: 18, width: 18 },
  uncheckIconStyle: { height: 20, width: 20 },
  expanContainer: {
    paddingHorizontal: 20,
    marginTop: 10,
  },
  plusIconStyle: { height: 10, width: 10, tintColor: colors.white },
  backIconStyle: { tintColor: colors.black },
  maskImagesContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 30,
    marginTop: 10,
  },
  maskImageStyle: {
    height: 100,
    //width: '48%',
    resizeMode: "cover",
    borderRadius: 15,
  },
  backArrowIcon: {
    width: moderateScale(width / 16),
    height: moderateScale(width / 16),
  },
  container: {
    flex: 1,
  },
  preview: {
    height: "100%",
    width: "100%",
    borderRadius: 40,
  },
  capture: {
    borderRadius: 20,
    alignSelf: "center",
    margin: 20,
    paddingVertical: 7,
    justifyContent: "center",
    alignItems: "center",
  },
  btnTextStyle: {
    fontSize: 14,
    color: colors.white,
    fontWeight: "600",
  },
  heaingStyle: {
    fontSize: 18,
    color: "black",
    fontWeight: "bold",
    marginTop: 30,
    textAlign: "center",
  },
  openCamerasheetMainContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  cameraSheetCustomStyle: {
    wrapper: {
      backgroundColor: colors.modalColor,
    },
    draggableIcon: {
      backgroundColor: "#000",
    },
    container: {
      borderTopLeftRadius: 5,
      borderTopRightRadius: 5,
      backgroundColor: "white",
    },
  },
  titleContainer: { flex: 0.1 },
  cameraContainer: {
    flex: 0.7,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
  },
  buttonsContainer: { flex: 0.2 },
  showImageContainer: { height: "90%", width: "90%" },
  imageStyle: { flex: 1 },
  cameraViewContainer: {
    flex: 1,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  rotateCameraButtonContainer: { flex: 1 },
  rotateCameraButton: {
    height: 40,
    width: 40,
    backgroundColor: "white",
    marginLeft: 20,
    marginTop: 20,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  rotateCameraIcon: { height: 30, width: 30 },
  submitButtonContainerRow: {
    flex: 0.1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginTop: 20,
  },
  buttonBoxContainer: { width: "48%" },
  cancelButtonStyle: {
    backgroundColor: colors.lightGary,
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.lightGary,
  },
  cancelButtonText: {
    fontSize: 14,
    color: colors.black,
    fontWeight: "600",
  },
  nextButtonStyle: {
    backgroundColor: colors.themeColor,
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    borderRadius: 10,
  },
  loaderContainer: {
    backgroundColor: colors.themeColor,
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    borderRadius: 10,
  },
  withMaskButton: {
    backgroundColor: colors.themeColor,
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    borderRadius: 10,
  },
  withoutMaskButton: {
    backgroundColor: colors.themeColor,
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    borderRadius: 10,
  },
  showMaskImagesContainer: { width: "48%" },
});
