import { StyleSheet } from "react-native";
import colors from "../../../styles/colors";
import { height, moderateScale, width } from "../../../styles/responsiveSize";

export const styles = StyleSheet.create({
  topContainer: { height: 150 },
  bgImageStyle: {
    height: "100%",
    width: "100%",
    backgroundColor:colors.themeColor
    // flexDirection: "row",
    // justifyContent: "space-between",
    // alignItems: "center",
  },
  backButtonStyle: {
    height: 40,
    width: 40,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.white,
    borderRadius: 30,
  },
  bottomContainer: {
    width: "100%",
    backgroundColor: colors.lightGary,
    alignItems: "center",
    flex: 1,
  },
  headerTitleText: {
    color: colors.white,
    marginLeft: 10,
    fontSize: 18,
    fontWeight: "bold",
  },
  backButtonContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
    paddingHorizontal: 20,
    width: width,
  },
  contentSectionContainer: {
    //height: "100%",
    width: "95%",
    backgroundColor: colors.white,
    marginTop: -80,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    paddingHorizontal: 15,
    paddingVertical: 20,
  },
  fromToContainer: { width: "100%" },
  fromAddressContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 5,
  },
  toAddressIndicator: {
    height: 8,
    width: 8,
    backgroundColor: colors.greenColor,
    borderRadius: 10,
  },
  addressText: { fontSize: 10, marginLeft: 5, color: colors.black },
  dotIndicator: {
    height: 5,
    width: 5,
    backgroundColor: colors.lightGray,
    marginLeft: 1,
    borderRadius: 10,
    marginVertical: 1,
  },
  toAddressContainer: {
    flexDirection: "row",
    marginTop: 5,
    alignItems: "center",
  },
  fromAddressIndicator: {
    height: 8,
    width: 8,
    backgroundColor: colors.orangeColor,
    borderRadius: 10,
    marginTop: 5,
  },
  fromToButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: 10,
  },
  plusButtonContainer: {
    height: 20,
    width: 20,
    borderWidth: 1,
    borderColor: colors.lightGary,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  plusTexT: { fontSize: 10, color: colors.black },
  supportButtonContainer: {
    borderWidth: 1,
    borderColor: colors.lightGary,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 15,
    flexDirection: "row",
  },
  supportText: {
    fontSize: 12,
    color: colors.black,
  },
  backIconStyle: { tintColor: colors.black },
  trackingIdTextStyle: { color: colors.white, marginLeft: 10 },
  dotIndicatorContainer: { flexDirection: "row" },
  bottomSheetContainer: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  listItemRow: {
    flexDirection: "row",
  },
  trackingLineContainer: {
    width: "10%",
    alignItems: "center",
  },
  completedTrackingLine: {
    height: 10,
    width: 2,
    backgroundColor: colors.greenColor2,
  },
  mapContainer: {
    height: 350,
    width: "100%",
    marginTop: 20,
  },
  mapView: { height: "100%", width: "100%" },
  detailContainer: { marginTop: 20 },
  divier: {
    height: 1,
    width: "100%",
    backgroundColor: colors.lightGary,
    marginVertical: 12,
  },
  detailRow: { flexDirection: "row", alignItems: "center" },
  iconStyle: { height: 25, width: 25, tintColor: colors.darkGray },
  iconTextStyle: {
    marginHorizontal: 20,
    fontWeight: "500",
    color: colors.black,
  },
  supportIconStyle: { height: 13, width: 13, marginHorizontal: 2 },
  unreachedDotIndicatorStyle: {
    height: 5,
    width: 5,
    backgroundColor: colors.lightGray,
    marginLeft: 1,
    borderRadius: 10,
    marginVertical: 3,
  },
  userImageStyle: { height: 35, width: 35, borderRadius: 30 },
  reachedIndicatorLine: { height: 30, width: 2, backgroundColor: colors.green },
  detailCoontainer: { width: "90%" },
  detailContainerRow: { flexDirection: "row", paddingTop: 5 },
  nameAndAddressContainer: { width: "65%" },
  timeScheduleContainer: { width: "35%" },
  timeScheduleContainerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  timeTextStyle: { fontSize: 12, color: colors.black },
  listItemSeperator: {
    width: "100%",
    backgroundColor: colors.lightGary,
    marginLeft: -10,
    marginTop: 10,
  },
  listItemAddressTextStyle: { fontSize: 12, marginTop: -1 },
  genderIconStyle: { height: 15, width: 15 },
  genderIconContainer: {
    height: 25,
    width: 25,
    borderWidth: 2,
    borderColor: colors.lightGary,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  vaccineIconStyle: { height: 15, width: 15 },
  vaccineIconContainer: {
    height: 25,
    width: 25,
    borderWidth: 2,
    borderColor: colors.lightGary,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 3,
  },
  ratingContainer: {
    width: "49%",
    flexDirection: "row",
    alignItems: "center",
  },
  verticalDivier: {
    height: 20,
    width: 1,
    backgroundColor: colors.lightGary,
  },
  ratingTextStyle: { marginLeft: 5, fontSize: 12 },
  genderAndVaccineIconContainer: {
    width: "49%",
    flexDirection: "row",
    alignItems: "center",
  },
  genderRatingVaccineRowStyle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  empNameTextStyle: { fontSize: 13, color: colors.black },
  crossIconStyle: {
    height: 20,
    width: 20,
    tintColor: colors.SOSSwipeBottonColor1,
  },
  backArrowIconStyle: {
    width: moderateScale(width / 16),
    height: moderateScale(width / 16),
  },
  tripIconAndIdContainer: { flexDirection: "row", alignItems: "center" },
  tripIconContainer: {
    backgroundColor: "white",
    marginLeft: 10,
    paddingHorizontal: 5,
    borderRadius: 5,
  },
  tripIconStyle: { height: 15, width: 15 },
  scrollViewContainer: { height: "100%" },
  rowContainer: { flexDirection: "row" },
  rowContainerLeftBox: {
    width: "5%",
    alignItems: "center",
  },
  dotContainer: { marginTop: 3 },
  dotIndicatorStyle: {
    height: 5,
    width: 5,
    backgroundColor: colors.lightGray,
    borderRadius: 10,
    marginVertical: 2,
  },
  rowContainerRightBox: { width: "95%" },
  addressContainer: { width: "80%" },
  showMoreContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 5,
  },
  snapShotStyle: {
    width: moderateScale(width / 1.15),
    height: moderateScale(height / 2.5),
  },
  empDetailContainer: {
    flexDirection: "row",
    marginHorizontal: 20,
    borderLeftWidth: 1,
    borderLeftColor: colors.greenColor,
    paddingBottom: 10,
  },
  empImageContainer: {
    height: 42,
    width: 42,
    marginLeft: -20,
    backgroundColor: "white",
    borderWidth: 2,
    borderColor: colors.veryLightGray,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
  },
  empImageStyle: { height: 35, width: 35, borderRadius: 20 },
  stopPointDetailContainer: {
    marginLeft: 10,
    borderBottomColor: "#f4f4f4",
    borderBottomWidth: 1,
    paddingBottom: 10,
    width: "90%",
  },
  noddlePointDetailContainer: {
    marginLeft: 10,
    borderBottomColor: "#f4f4f4",
    borderBottomWidth: 1,
    paddingBottom: 10,
    width: "90%",
    justifyContent: "center",
  },
  rowConntainer: { flexDirection: "row" },
  leftBoxWidth: { width: "60%" },
  rightBoxWidth: {
    width: "40%",
    alignItems: "center",
    flexDirection: "row",
  },
  stopPointETATimeContainer: { width: "50%", alignItems: "center" },
  stopPointETAAlignment: { alignItems: "center" },
  stopPointArrivalTimeContainer: {
    width: "50%",
    justifyContent: "center",
    alignItems: "center",
  },
  arrivalTimeETAContainer: {
    width: "50%",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  absentIconStyle: { height: 40, width: 40 },
  absentTimeStyle: { color: colors.black, fontSize: 10 },
  skipAndNoShowEmpIcon: { height: 25, width: 25 },
  vehicleDelayAndOnTimeIcon: { height: 20, width: 20 },
  delayTimeContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 5,
  },
  delayAndEarlyIconStyle: { height: 15, width: 15 },
  rightBoxWidthForVehicleAndEmpDelay: { width: "40%" },
  vehicleAndEmpDelayContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  vehicleDelayIconStyle: { height: 20, width: 20, marginLeft: 10 },
  noddleIconStyle: { height: 30, width: 30 },
  officeIconStyle: { height: 35, width: 35 },
  verticalDeviderContainer: { marginHorizontal: 10 },
  showMoreDetailContainer: {
    marginTop: 10,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingRight: 20,
  },
  shoeMoreLeftBox: {
    flexDirection: "row",
    alignItems: "center",
    width: "70%",
  },
  showMoreRightBox: {
    width: "30%",
    justifyContent: "center",
    alignItems: "center",
  },
  showMoreGroupIcon: { height: 20, width: 20 },
  showMoreNumberEmpText: { color: colors.black },
  showMoreEmpDetailContainer: {
    borderBottomColor: "#f4f4f4",
    borderBottomWidth: 1,
    paddingVertical: 10,
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
  },
  showMoreEmpDetailLeftBox: {
    width: "72%",
    flexDirection: "row",
  },
  showMoreEmpDetailRightBox: {
    width: "28%",
    justifyContent: "center",
    alignItems: "center",
  },
  showMoreEmpNameContainer: { marginLeft: 10 },
  showMoreEmpNameText: {
    color: colors.black,
    fontWeight: "400",
    fontSize: 13,
  },
  showMoreRatingAndIconContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  empStatusContainer: {
    paddingHorizontal: 5,
    paddingVertical: 4,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.SOSSwipeBottonColor1,
  },
  empStatusText: {
    color: colors.white,
    fontSize: 12,
    textTransform: "capitalize",
  },
  empDelayContainer: {
    width: "100%",
    alignSelf: "center",
  },
  livetripTrackingSheetStatusContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  trackingBottomSheetCustomStyle: {
    container: {
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
  },
  trackingBottomSheetFlatListContainer: { flex: 1 },
  textColor: { marginTop: 5, color: colors.black },
  containerAlignment: {
    justifyContent: "center",
    alignItems: "center",
  },
  tollContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  tollStatusIcon: {
    height: 20,
    width: 20,
  },
  linkTextContainer: {
    width: "65%",
  },
  amountAndStatusContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "33%",
  },
});
