export default {
  WELCOME_SCREEN: "WelcomeScreen",
  LOGIN: "Login",
  OTP: "Otp",
  UPDATE_PROFILE: "UpdateProfile",
  UPDATE_PROFILE_DOC: "UpdateProfileDoc",
  HOME_STACK: "HomeStack",
  HOME: "Home",
  DRAWER_NAV: "DrawerNav",
  UPCOMING_TRIPS: "Upcoming Trips",
  VERIFY_DRIVER_DOC: "VerifyDriverDoc",
  VERIFY_AND_UPDATE_FIRST: "VerifyAndUpdateFirst",
  VERIFY_AND_UPDATE_SECOND: "VerifyAndUpdateSecond",
  DRIVER_SELF_CONCENT: "DriverSelfConcent",
  LIVE_TRACKING: "LiveTracking",
  TRIP_DETAIL: "TripDetail",
  YOUR_RIDES: "YourRides",
  SETTINGS: "Settings",
  SUPPORT: "Support",
  TICKET_LISTING: "Ticket Listing",
  SUPPORT_TICKETS_DETAILS: "Support Ticket Detail",
  CHOOSE_AN_ISSUE: "ChooseAnIssue",
  SELECTED_ISSUE: "Selected Issue",
  TELL_US_ABOUT_IT: "Tell us about it",
  NOTIFICATIONS: "Notifications",
  PRIVACY_POLICY: "PrivacyPolicy",
  CHOOSE_LOCATION: "Choose Location",
  CHOOSE_LOCATION_FIRST: "Choose Location First",
  COMPLIANCE: "Compliance",
  RATING_AND_FEEDBACK: "Rating And Feedback",
  STATES: "States",
  ABOUT: "About",
  WEBVIEW: "WebView",
  FILTERED_RIDE: "FilteredRide",
  TRAINING_VIDEOS: "Training Videos",
  TOLL_TAX_AND_PARKING: "Toll Tax And Parking",
  TRIP_TOLL_TAX_AND_PARKING: "Toll Tax And Parking",
  WRITE_TO_US: "Write to us",
  SELECTED_ISSUE: "Selected Issue",
  TELL_US_ABBOUT_IT: "Tell us about it",
  SELECTED_SUPPORT_ISSUE: "Selected Support Issue",
  NEXT_SUPPORT_ISSUE: "Next Support Issue",
  LEARN_MORE: "Learn More",
  TICKET_LISTING: "TicketListing",
  SUPPORT_TICKETS_DETAILS: "SUPPORT_TICKETS_DETAILS",
  FUELTRACKING: "Fuel Tracking",
  ADD_FUEL: "Add Fuel",
  DRIVER_ATTENDENCE: "Driver Attendence",
};
